language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/php-cs-fixer fix lib/ --dry-run --diff

before_script: composer install --dev
